### ISSUE TITLE
Cannot use with registerMethod

### ISSUE THREAD

**Issue by westlakem** [dodevops/node-rest-client-promise#1]
Trying to convert an app that uses `client.registerMethod` and then `client.methods` to call the URI.  It doesn't seem to work with this package.

**Comment by dploeger** [comment]
What errors are you getting or what exactly doesn't seem to work?

**Comment by westlakem** [comment]
I don't remember off the top of my head... I switched to using `request` which handled the use case just fine.

**Comment by dploeger** [comment]
Hm. Closing this one then.
