### ISSUE TITLE
Support for node-rest-client's registerMethod is missing

### ISSUE THREAD

**Issue by dreamgear** [dodevops/node-rest-client-promise#2]
Greetings. I’ve tried out node-rest-client-promise but found I need to be able to use the registerMethod functionality in node-rest-client. If this were ever added to node-rest-client-promise I’d be grateful

**Comment by dploeger** [comment]
This method is supported as registerMethodPromise in the latest version 3.1.0. Could you please test, if it meeds your requirements?

**Comment by dreamgear** [comment]
Will do.  Thanks.

**Comment by bstoots** [comment]
I have confirmed that registerMethodPromise works in version 3.1.0.  It would probably be helpful to have some additional documentation on usage though, particularly for people just skimming the README.

**Comment by dploeger** [comment]
Did just that. Thanks everybody.
