### ISSUE TITLE
OTHER HTTPS METHOD

### ISSUE THREAD

**Issue by HiepNinh** [dodevops/node-rest-client-promise#5]
How to using node-rest-client-promise with other methods such as POST, DELETE, PUT, GET with request data,... I can't find docs or references anywhere. Thanks in advance

**Comment by dploeger** [comment]
As the documentation states, this is just a promisified wrapper for [node-rest-client](https://www.npmjs.com/package/node-rest-client), which has methods like `client.get` which become `client.getPromise` here. This means, that `client.post` becomes `client.postPromise` here and so on.
